//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnimalAdoption.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AnimalAdoption.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Adsız_tasarım__2_ {
            get {
                object obj = ResourceManager.GetObject("Adsız tasarım (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Adsız_tasarım__2_1 {
            get {
                object obj = ResourceManager.GetObject("Adsız tasarım (2)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Adsız_tasarım__3_ {
            get {
                object obj = ResourceManager.GetObject("Adsız tasarım (3)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cake_24dp_FILL0_wght400_GRAD0_opsz24__1_ {
            get {
                object obj = ResourceManager.GetObject("cake_24dp_FILL0_wght400_GRAD0_opsz24 (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cropped_animals_banner_800x223 {
            get {
                object obj = ResourceManager.GetObject("cropped-animals-banner-800x223", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit_20dp_FILL0_wght400_GRAD0_opsz20 {
            get {
                object obj = ResourceManager.GetObject("edit_20dp_FILL0_wght400_GRAD0_opsz20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file {
            get {
                object obj = ResourceManager.GetObject("file", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file__1_ {
            get {
                object obj = ResourceManager.GetObject("file (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file__2_ {
            get {
                object obj = ResourceManager.GetObject("file (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap home_24dp_FILL0_wght400_GRAD0_opsz24 {
            get {
                object obj = ResourceManager.GetObject("home_24dp_FILL0_wght400_GRAD0_opsz24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap home_24dp_FILL0_wght400_GRAD0_opsz24__1_ {
            get {
                object obj = ResourceManager.GetObject("home_24dp_FILL0_wght400_GRAD0_opsz24 (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap how_to_reg_20dp_FILL0_wght400_GRAD0_opsz20 {
            get {
                object obj = ResourceManager.GetObject("how_to_reg_20dp_FILL0_wght400_GRAD0_opsz20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap how_to_reg_20dp_FILL0_wght400_GRAD0_opsz201 {
            get {
                object obj = ResourceManager.GetObject("how_to_reg_20dp_FILL0_wght400_GRAD0_opsz201", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap id_card_24dp_FILL0_wght400_GRAD0_opsz24__1_ {
            get {
                object obj = ResourceManager.GetObject("id_card_24dp_FILL0_wght400_GRAD0_opsz24 (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap location_city_24dp_FILL0_wght400_GRAD0_opsz24__1_ {
            get {
                object obj = ResourceManager.GetObject("location_city_24dp_FILL0_wght400_GRAD0_opsz24 (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lock_24dp_FILL0_wght400_GRAD0_opsz24__1_ {
            get {
                object obj = ResourceManager.GetObject("lock_24dp_FILL0_wght400_GRAD0_opsz24 (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lock_24dp_FILL0_wght400_GRAD0_opsz24__1_1 {
            get {
                object obj = ResourceManager.GetObject("lock_24dp_FILL0_wght400_GRAD0_opsz24 (1)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lock_24dp_FILL0_wght400_GRAD0_opsz24__1_2 {
            get {
                object obj = ResourceManager.GetObject("lock_24dp_FILL0_wght400_GRAD0_opsz24 (1)2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap login_20dp_FILL0_wght400_GRAD0_opsz20 {
            get {
                object obj = ResourceManager.GetObject("login_20dp_FILL0_wght400_GRAD0_opsz20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap login_24dp_FILL0_wght400_GRAD0_opsz24 {
            get {
                object obj = ResourceManager.GetObject("login_24dp_FILL0_wght400_GRAD0_opsz24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap login_24dp_FILL0_wght400_GRAD0_opsz24__1_ {
            get {
                object obj = ResourceManager.GetObject("login_24dp_FILL0_wght400_GRAD0_opsz24 (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap person_24dp_FILL0_wght400_GRAD0_opsz24__1_ {
            get {
                object obj = ResourceManager.GetObject("person_24dp_FILL0_wght400_GRAD0_opsz24 (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap person_24dp_FILL0_wght400_GRAD0_opsz24__1_1 {
            get {
                object obj = ResourceManager.GetObject("person_24dp_FILL0_wght400_GRAD0_opsz24 (1)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_computer_icons_symbol_login_register_button_miscellaneous_logo_thumbnail {
            get {
                object obj = ResourceManager.GetObject("png-clipart-computer-icons-symbol-login-register-button-miscellaneous-logo-thumbn" +
                        "ail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap settings_24dp_FILL0_wght400_GRAD0_opsz24 {
            get {
                object obj = ResourceManager.GetObject("settings_24dp_FILL0_wght400_GRAD0_opsz24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
